### ISSUE TITLE
Can't paste text

### ISSUE THREAD

**Issue by bebaps** [erwstout/android-messages#1]
Maybe this has something to do with Electron. I opened a Google Sheet in Chrome. I selected some content and copied into the clipboard (`cmd+c`). I can't paste that content into the Electron app, but can paste it anywhere else on my computer (Chrome, Safari, another Mac OSX app, etc...) via `cmd+v`. I am using Mac OSX Mojave.

With Android Messages, I can paste content into the browser tab (via https://messages.android.com/ within Chrome) but not into the Electron wrapper.

**Comment by bebaps** [comment]
This may provide insight: https://github.com/electron/electron/blob/master/docs/api/clipboard.md#clipboard

**Comment by erwstout** [comment]
Thanks @bebaps, I think I have a solution. I'll try to get to it soon.
